const sampleProducts = [
    {
        categoryId: 1,
        name: 'Apple iPhone 13 Pro Max',
        description: 'The iPhone 13 Pro Max offers a 6.7-inch Super Retina display, 128GB of storage, and 5G connectivity.',
        price: 1099.99,
        totalStock: 50,
        imageUrl: ['/uploads/iphone13promax.jpg'],
    },
    {
        categoryId: 2,
        name: 'Samsung Galaxy S21 Ultra',
        description: 'With a 6.8-inch display, 128GB storage, and a powerful 108MP camera, the Galaxy S21 Ultra is made for photographers.',
        price: 1199.99,
        totalStock: 60,
        imageUrl: ['/uploads/galaxys21ultra.jpg'],
    },
    {
        categoryId: 3,
        name: 'Sony WH-1000XM4 Noise Cancelling Headphones',
        description: 'Industry-leading noise cancellation, crystal clear sound, and up to 30 hours of battery life.',
        price: 349.99,
        totalStock: 100,
        imageUrl: ['/uploads/sonyheadphones.jpg'],
    },
    {
        categoryId: 4,
        name: 'Dell XPS 13 Laptop',
        description: '13.4-inch FHD+ display, Intel Core i7, 16GB RAM, 512GB SSD, perfect for professionals on the go.',
        price: 1499.99,
        totalStock: 30,
        imageUrl: ['/uploads/dellxps13.jpg'],
    },
    {
        categoryId: 1,
        name: 'Apple Watch Series 7',
        description: 'Sleek design with a larger display, faster charging, and advanced health monitoring features.',
        price: 399.99,
        totalStock: 75,
        imageUrl: ['/uploads/applewatch7.jpg'],
    },
    {
        categoryId: 2,
        name: 'Samsung Galaxy Buds Pro',
        description: 'Premium sound quality, noise cancellation, and a comfortable fit make these earbuds perfect for any activity.',
        price: 199.99,
        totalStock: 120,
        imageUrl: ['/uploads/galaxybudspro.jpg'],
    },
    {
        categoryId: 3,
        name: 'Bose QuietComfort 35 II',
        description: 'With world-class noise cancellation and a comfortable over-ear design, these headphones are ideal for travel.',
        price: 299.99,
        totalStock: 80,
        imageUrl: ['/uploads/boseqc35ii.jpg'],
    },
    {
        categoryId: 4,
        name: 'Microsoft Surface Laptop 4',
        description: '13.5-inch PixelSense display, Intel Core i5, 8GB RAM, and a long battery life for a productive day.',
        price: 1199.99,
        totalStock: 40,
        imageUrl: ['/uploads/surfacelaptop4.jpg'],
    },
    {
        categoryId: 1,
        name: 'GoPro HERO10 Black',
        description: 'Capture stunning 5.3K video, 23MP photos, and excellent stabilization with the HERO10 Black.',
        price: 499.99,
        totalStock: 100,
        imageUrl: ['/uploads/goprohero10.jpg'],
    },
    {
        categoryId: 2,
        name: 'Fitbit Charge 5',
        description: 'A sleek fitness tracker with built-in GPS, heart rate monitor, and sleep tracking features.',
        price: 179.99,
        totalStock: 150,
        imageUrl: ['/uploads/fitbitcharge5.jpg'],
    },
    {
        categoryId: 3,
        name: 'JBL Charge 5 Portable Bluetooth Speaker',
        description: 'With 20 hours of playtime, waterproof design, and superior sound, the JBL Charge 5 is your perfect travel companion.',
        price: 179.99,
        totalStock: 200,
        imageUrl: ['/uploads/jblcharge5.jpg'],
    },
    {
        categoryId: 4,
        name: 'Lenovo ThinkPad X1 Carbon',
        description: 'A powerful and lightweight 14-inch laptop with Intel Core i7, 16GB RAM, and a durable build.',
        price: 1899.99,
        totalStock: 25,
        imageUrl: ['/uploads/lenovothinkpadx1.jpg'],
    },
    {
        categoryId: 1,
        name: 'iPad Pro 12.9-inch (5th Generation)',
        description: 'The iPad Pro features an M1 chip, 12.9-inch Liquid Retina XDR display, and supports Apple Pencil.',
        price: 1099.99,
        totalStock: 60,
        imageUrl: ['/uploads/ipadpro12.jpg'],
    },
    {
        categoryId: 2,
        name: 'Apple AirPods Pro (2nd Generation)',
        description: 'Active Noise Cancellation, Transparency mode, and up to 6 hours of listening time with a single charge.',
        price: 249.99,
        totalStock: 150,
        imageUrl: ['/uploads/airpodspro2.jpg'],
    },
    {
        categoryId: 3,
        name: 'Harman Kardon Onyx Studio 6 Bluetooth Speaker',
        description: 'Stylish and powerful with a 6-hour battery life, perfect for parties or home use.',
        price: 399.99,
        totalStock: 80,
        imageUrl: ['/uploads/harmankardononyx6.jpg'],
    },
    {
        categoryId: 4,
        name: 'HP Spectre x360 14',
        description: 'Convertible 2-in-1 laptop with a 14-inch OLED display, Intel Core i7, and 16GB of RAM.',
        price: 1599.99,
        totalStock: 40,
        imageUrl: ['/uploads/hpspectrex360.jpg'],
    },
    {
        categoryId: 1,
        name: 'Apple MacBook Air (M1 Chip)',
        description: 'The 13.3-inch MacBook Air features Apple’s M1 chip, 8GB RAM, and all-day battery life.',
        price: 999.99,
        totalStock: 50,
        imageUrl: ['/uploads/macbookairm1.jpg'],
    },
    {
        categoryId: 2,
        name: 'Sony PlayStation 5',
        description: 'The latest gaming console from Sony, featuring stunning graphics, fast load times, and exclusive games.',
        price: 499.99,
        totalStock: 200,
        imageUrl: ['/uploads/ps5.jpg'],
    },
    {
        categoryId: 3,
        name: 'Razer DeathAdder V2 Gaming Mouse',
        description: 'Precision optical sensor, ultra-fast response time, and customizable RGB lighting make this the ultimate gaming mouse.',
        price: 69.99,
        totalStock: 300,
        imageUrl: ['/uploads/razerdeathadderv2.jpg'],
    },
    {
        categoryId: 4,
        name: 'Corsair Vengeance LPX 16GB (2 x 8GB) DDR4 RAM',
        description: 'High-performance RAM with a sleek heat spreader, ideal for gaming and intensive applications.',
        price: 89.99,
        totalStock: 150,
        imageUrl: ['/uploads/corsairvengeance.jpg'],
    },
    {
        categoryId: 1,
        name: 'Sony A7 III Mirrorless Camera',
        description: 'Full-frame mirrorless camera with a 24.2MP sensor, 4K video recording, and exceptional autofocus.',
        price: 1999.99,
        totalStock: 30,
        imageUrl: ['/uploads/sonya7iii.jpg'],
    },
    {
        categoryId: 2,
        name: 'Nintendo Switch OLED Model',
        description: 'The Nintendo Switch OLED model features a 7-inch OLED screen, improved audio, and a more stable kickstand.',
        price: 349.99,
        totalStock: 80,
        imageUrl: ['/uploads/nintendoswitcholed.jpg'],
    },
    {
        categoryId: 3,
        name: 'Amazon Echo Studio',
        description: 'A premium smart speaker with 3D audio, Dolby Atmos, and Alexa integration.',
        price: 199.99,
        totalStock: 100,
        imageUrl: ['/uploads/echo-studio.jpg'],
    },
    {
        categoryId: 4,
        name: 'Logitech MX Master 3 Wireless Mouse',
        description: 'Ergonomically designed wireless mouse with customizable buttons and long battery life.',
        price: 99.99,
        totalStock: 120,
        imageUrl: ['/uploads/logitechmxmaster3.jpg'],
    },
    {
        categoryId: 1,
        name: 'Canon EOS 90D DSLR Camera',
        description: 'A DSLR with a 32.5MP sensor, 4K video recording, and fast autofocus, perfect for photography and vlogging.',
        price: 1299.99,
        totalStock: 40,
        imageUrl: ['/uploads/canon90d.jpg'],
    },
    {
        categoryId: 2,
        name: 'Google Pixel 6 Pro',
        description: 'Google’s flagship smartphone with a 6.7-inch OLED display, Tensor chip, and 5G connectivity.',
        price: 899.99,
        totalStock: 60,
        imageUrl: ['/uploads/googlepixel6pro.jpg'],
    },
    {
        categoryId: 3,
        name: 'Bose SoundLink Revolve+ Bluetooth Speaker',
        description: '360-degree sound, 16 hours of battery life, and a water-resistant design make this speaker ideal for any environment.',
        price: 299.99,
        totalStock: 50,
        imageUrl: ['/uploads/bosesoundlinkrevolve.jpg'],
    },
    {
        categoryId: 4,
        name: 'Apple Mac Mini (M1 Chip)',
        description: 'Compact desktop with Apple’s M1 chip, 8GB RAM, and exceptional performance for professional work.',
        price: 699.99,
        totalStock: 80,
        imageUrl: ['/uploads/macminiM1.jpg'],
    }
];

module.exports = sampleProducts;
